DROP TABLE IF EXISTS INVOICE;

CREATE TABLE INVOICE (
  INVOICE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  AMOUNT INT NOT NULL,
  CURRENCY VARCHAR(10) NOT NULL
);

CREATE TABLE CARD (
    CARD_ID INT AUTO_INCREMENT  PRIMARY KEY,
    PAN VARCHAR(100) NOT NULL,
    EXPIRY VARCHAR(10) NOT NULL
);

CREATE TABLE CARD_HOLDER (
    CARD_HOLDER_ID INT AUTO_INCREMENT  PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL
);

CREATE TABLE INVOICE_CARD (
    INVOICE_ID INT,
    CARD_ID INT
);
CREATE TABLE INVOICE_CARDHOLDER (
    INVOICE_ID INT,
    CARD_HOLDER_ID INT
);
